name: python_pypline_basic
env:
  FILE_NAME: "my_python_project/output.txt"
on:
  push:
    branches: [main]
jobs:
  my_tests:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing started
      run: echo "Testing started" 
    
    - name: Test execution
      run: cd my_python_project && echo "Tests results of testing latest updates after pushed changes in master of ${{ github.repository }} is" > output.txt && python3 -m unittest discover tests &>> output.txt

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: ${{ env.FILE_NAME }}
      env:
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}





  my_build:
    runs-on: ubuntu-latest
    needs: [my_tests]
    steps:
    - name: Building started
      run: echo "Building started" 
