name: python_pypline_basic
on:
  push:
    branches: [main]
jobs:
  my_tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing started
      run: echo "Testing started" 
    
    - name: Test execution
      run: ls && cd my_python_project && python -m unittest discover tests





  my_build:
    runs-on: ubuntu-latest
    needs: [my_tests]
    steps:
    - name: Building started
      run: echo "Building started" 
