name: python_pypline_basic
on:
  push:
    branches: [main]
jobs:
  my_tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing started
      run: echo "Testing started" 
    
    - name: Test execution
      run: ls && cd my_python_project && echo "Tests result is:" > output.txt && python -m unittest discover tests >> output.txt

    - name: send telegram message on push
    - uses: appleboy/telegram-action@0.0.3
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: output.txt





  my_build:
    runs-on: ubuntu-latest
    needs: [my_tests]
    steps:
    - name: Building started
      run: echo "Building started" 
